%
% Output of type 3 from the ABAQUS results file to MATLAB
%
% Syntax
%     [#outNum#,#outStr#,#m#,#k#]=readFilCat3(#Rec#,#recordKey#,zeros(1,0),zeros(1,0),char(zeros(1,0)),zeros(1,0),zeros(1,0))
%
% Description
%     Read type 3 output from an Abaqus results file generated from the
%     ABAQUS finite element software. The possible values of recordKey can
%     be found from Table in section 3.2.2.2 of Abaqus2Matlab
%     documentation. The output of type 3 corresponds to records containing
%     both numerical values (floating point numbers or integers) and
%     strings. Also, records containing only floating point numbers or only
%     strings can be processed by this function. In the former case, the
%     function readFilCat1 is more appropriate and faster. In the latter
%     case, this function can be used with no problems. See section ''5.1.2
%     Results file output format'' in ABAQUS Analysis User's manual for
%     more details.
%     Dummy input arguments are required for execution of this function, as
%     illustrated in the 'Input parameters' section below. These are used
%     for memory allocation issues and proper initialization of internal
%     variables.
%
% Input parameters
%     REQUIRED:
%     #Rec# (string) is a one-row string containing all the data inside the
%         Abaqus results file. The results file is generated by Abaqus
%         after the analysis has been completed.
%     #recordKey# (integer) is an integer equal to the record key of
%         the requested result. See the documentation for the possible
%         record keys for the extraction of results of type 3.
%     DUMMY (in the following order, after REQUIRED):
%     zeros(1,0)
%     zeros(1,0)
%     char(zeros(1,0))
%     zeros(1,0)
%     zeros(1,0)
%
% Output parameters
%     #outNum# ([#n# x numel(#m#)]) is a double array containing the
%         numeric values of each record printed in the results file. #n# is
%         the number of records being processed by the function.
%     #outStr# ([#n# x numel(#k#)]) is a string array containing the string
%         values of each record printed in the results file.
%     #m# ([1 x numel(#m#)]) contains the indices of the attributes in each
%         record which correspond to numeric values (floating points and
%         integers). For example if a record with four attributes (NW=6)
%         contains one numerical value in its 3rd position, one string in
%         its 4th position and two numeric values at its 5th and 6th
%         positions, then #m# would be [1 3 4] and #k# would be [9 10 11 12
%         13 14 15 16].
%     #k# ([1 x numel(#k#)]) contains the indices of the characters of the
%         strings contained as attributes in each record. Since in the
%         results file the string output appears in A8 format (or
%         multiples) #k# contains 8 elements for each string attribute and
%         numel(#k#) will be always a multiple of 8. For example, if a
%         record with four attributes (NW=6) contains numerical values at
%         its 1st and 3rd positions, and strings at its 2nd and 4th
%         positions, then #k# would be [9 10 11 12 13 14 15 16 25 26 27 28
%         29 30 31 32] and #m# would be [1 3].
%
% _________________________________________________________________________
% Abaqus2Matlab - www.abaqus2matlab.com
% Copyright (c) 2017 by George Papazafeiropoulos
%
% If using this toolbox for research or industrial purposes, please cite:
% G. Papazafeiropoulos, M. Muniz-Calvente, E. Martinez-Paneda.
% Abaqus2Matlab: a suitable tool for finite element post-processing.
% Advances in Engineering Software. Vol 105. March 2017. Pages 9-16. (2017)
% DOI:10.1016/j.advengsoft.2017.01.006

% Built-in function (Matlab R2012b)
