%
% ABAQUS label cross-reference output to MATLAB
% 
% Syntax
%     [#EleNum#,#EleType#]=Rec1940(#Rec#,zeros(1,0),zeros(1,0))
%
% Description
%     Read label cross-reference output from the results file generated
%     from the ABAQUS finite element software. The record key for label
%     cross-reference output is 1940. See section ''Results file output
%     format'' in ABAQUS Analysis User's manual for more details.
%     The following option with parameter has to be specified in the ABAQUS
%     input file for the results file to be created:
%         *FILE FORMAT, ASCII
%     Dummy input arguments are required for execution of this function, as
%     illustrated in the 'Input parameters' section below. These are used
%     for memory allocation issues and proper initialization of internal
%     variables.
%     
% Input parameters
%     REQUIRED:
%     #Rec# (string) is a one-row string containing all the data inside the
%         Abaqus results file. The results file is generated by Abaqus
%         after the analysis has been completed.
%     DUMMY (in the following order, after REQUIRED):
%     zeros(1,0)
%     zeros(1,0)
% 
% Output parameters
%     #EleNum# ([#n# x 1]) is a column vector containing the reference
%         integers of the attributes of the record key 1940.
%     #EleType# ([#n# x #m#]) is a string array having #m# characters per
%         row. Each row contains the label of the attributes of the record
%         key 1940 (10A8 format).
%     #n# is the number of elements.
%
% _________________________________________________________________________
% Abaqus2Matlab - www.abaqus2matlab.com
% Copyright (c) 2017 by George Papazafeiropoulos
%
% If using this toolbox for research or industrial purposes, please cite:
% G. Papazafeiropoulos, M. Muniz-Calvente, E. Martinez-Paneda.
% Abaqus2Matlab: a suitable tool for finite element post-processing.
% Advances in Engineering Software. Vol 105. March 2017. Pages 9-16. (2017) 
% DOI:10.1016/j.advengsoft.2017.01.006

% Built-in function (Matlab R2012b)
