%
% ABAQUS element definitions output to MATLAB
% 
% Syntax
%     [#EleNum#,#EleType#,#EleNodes#]=Rec1900(#Rec#,zeros(1,0),zeros(1,0))
%
% Description
%     Read element definitions output from the results file generated from
%     the ABAQUS finite element software. The record key for element
%     definitions output is 1900. See section ''Results file output
%     format'' in ABAQUS Analysis User's manual for more details.
%     The following option with parameter has to be specified in the ABAQUS
%     input file for the results file to be created:
%         *FILE FORMAT, ASCII
%     Dummy input arguments are required for execution of this function, as
%     illustrated in the 'Input parameters' section below. These are used
%     for memory allocation issues and proper initialization of internal
%     variables.
%     
% Input parameters
%     REQUIRED:
%     #Rec# (string) is a one-row string containing all the data inside the
%         Abaqus results file. The results file is generated by Abaqus
%         after the analysis has been completed.
%     DUMMY (in the following order, after REQUIRED):
%     zeros(1,0)
%     zeros(1,0)
% 
% Output parameters
%     #EleNum# ([#n# x 1]) is a column vector containing the element number
%         of each processed element
%     #EleType# ([#n# x 8]) is a string array having 8 characters per row.
%         Each row contains the element type in A8 format, left justified.
%     #EleNodes# ([#n# x #m#]) is an array containing the identities of the
%         nodes that define each element. #m# is the number of nodes per
%         element. If elements of different number of nodes are present in
%         the same model, then the node IDs of the elements defined by
%         number of nodes smaller than #m# are left justified, and the
%         trailing node positions are filled with zeros.
%
% _________________________________________________________________________
% Abaqus2Matlab - www.abaqus2matlab.com
% Copyright (c) 2017 by George Papazafeiropoulos
%
% If using this toolbox for research or industrial purposes, please cite:
% G. Papazafeiropoulos, M. Muniz-Calvente, E. Martinez-Paneda.
% Abaqus2Matlab: a suitable tool for finite element post-processing.
% Advances in Engineering Software. Vol 105. March 2017. Pages 9-16. (2017) 
% DOI:10.1016/j.advengsoft.2017.01.006

% Built-in function (Matlab R2012b)
