%
% ABAQUS analysis information output to MATLAB
%
% Syntax
%     [#Release#,#Date#,#Time#,#NEleNode#,#EleLength#]=Rec1921(#Rec#,zeros(1,0))
%
% Description
%     Read analysis information output from the results file generated from
%     the ABAQUS finite element software. The asterisk (*) is replaced by
%     the name of the results file. The record key for analysis information
%     output is 1921. See section ''Results file output format'' in ABAQUS
%     Analysis User's manual for more details.
%     The following option with parameter has to be specified in the ABAQUS
%     input file for the results file to be created:
%         *FILE FORMAT, ASCII
%     Dummy input arguments are required for execution of this function, as
%     illustrated in the 'Input parameters' section below. These are used
%     for memory allocation issues and proper initialization of internal
%     variables.
%
% Input parameters
%     REQUIRED:
%     #Rec# (string) is a one-row string containing all the data inside the
%         Abaqus results file. The results file is generated by Abaqus
%         after the analysis has been completed.
%     DUMMY (in the following order, after REQUIRED):
%     zeros(1,0)
%
% Output parameters
%     #Release# ([1 x 8]) is a row string which has 8 characters and
%         contains the Abaqus release number (A8 format)
%     #Date# ([1 x #m#]) is a row string which has #m# characters and
%         contains the date (2A8 format). #m#>=16.
%     #Time# ([1 x 8]) is a row string which has 8 characters and
%         contains the time (A8 format)
%     #NEleNode# ([1 x 2]) is a double array containing the number of the
%         elements and the number of the nodes in the model.
%     #EleLength# (scalar) is the typical element length in the model.
%
% _________________________________________________________________________
% Abaqus2Matlab - www.abaqus2matlab.com
% Copyright (c) 2017 by George Papazafeiropoulos
%
% If using this toolbox for research or industrial purposes, please cite:
% G. Papazafeiropoulos, M. Muniz-Calvente, E. Martinez-Paneda.
% Abaqus2Matlab: a suitable tool for finite element post-processing.
% Advances in Engineering Software. Vol 105. March 2017. Pages 9-16. (2017)
% DOI:10.1016/j.advengsoft.2017.01.006

% Built-in function (Matlab R2012b)
