%
% ABAQUS modal output to MATLAB
%
% Syntax
%     #out#=Rec1980(#Rec#,zeros(1,0),zeros(1,0))
%
% Description
%     Read modal output from the results file generated from the ABAQUS
%     finite element software. The record key for modal output is 1980 (in
%     ABAQUS/Standard) and is written once per eigenvalue in an
%     eigenanalysis step. See section ''Results file output format'' in
%     ABAQUS Analysis User's manual for more details. The following options
%     with parameters have to be specified in the ABAQUS input file for the
%     results file to be created and contain eigenanalysis results (#n# is
%     the number of requested eigenvalues):
%         *FREQUENCY
%          #n#
%         *FILE FORMAT, ASCII
%     Dummy input arguments are required for execution of this function, as
%     illustrated in the 'Input parameters' section below. These are used
%     for memory allocation issues and proper initialization of internal
%     variables.
%
% Input parameters
%     REQUIRED:
%     #Rec# (string) is a one-row string containing all the data inside the
%         Abaqus results file. The results file is generated by Abaqus
%         after the eigenanalysis has been completed.
%     DUMMY (in the following order, after REQUIRED):
%     zeros(1,0)
%     zeros(1,0)
%
% Output parameters
%     #out# ([#n# x 16]) is a double array containing the attributes of the
%         record key 1980 as follows:
%         Column  1  –  Eigenvalue number.
%         Column  2  –  Eigenvalue.
%         Column  3  –  Generalized mass.
%         Column  4  –  Composite damping.
%         Column  5  –  Participation factor for degree of freedom 1.
%         Column  6  –  Effective mass for degree of freedom 1.
%         Column  7  –  Participation factor for degree of freedom 2.
%         Column  8  –  Effective mass for degree of freedom 2.
%         Column  9  –  Participation factor for degree of freedom 3.
%         Column 10  –  Effective mass for degree of freedom 3.
%         Column 11  –  Participation factor for degree of freedom 4.
%         Column 12  –  Effective mass for degree of freedom 4.
%         Column 13  –  Participation factor for degree of freedom 5.
%         Column 14  –  Effective mass for degree of freedom 5.
%         Column 15  –  Participation factor for degree of freedom 6.
%         Column 16  –  Effective mass for degree of freedom 6.
%         where #n# is the number of requested eigenvalues in the frequency
%         extraction step. If the results file does not contain the desired
%         output, #out# will be an empty array.
%     ***NOTE: According to the Abaqus Analysis User's Manual, this record
%     is written if there are any results file output requests for an
%     eigenvalue buckling prediction or eigenfrequency extraction step.
%     Columns 3 - 16 are not written for an eigenvalue buckling prediction
%     step. This record is not written for a complex eigenfrequency
%     extraction step.
%
% _________________________________________________________________________
% Abaqus2Matlab - www.abaqus2matlab.com
% Copyright (c) 2017 by George Papazafeiropoulos
%
% If using this toolbox for research or industrial purposes, please cite:
% G. Papazafeiropoulos, M. Muniz-Calvente, E. Martinez-Paneda.
% Abaqus2Matlab: a suitable tool for finite element post-processing.
% Advances in Engineering Software. Vol 105. March 2017. Pages 9-16. (2017)
% DOI:10.1016/j.advengsoft.2017.01.006

% Built-in function (Matlab R2012b)
