%
% Output of type 1 from the ABAQUS results file to MATLAB
%
% Syntax
%     #out#=readFilCat1(#Rec#,#recordKey#,zeros(1,0),zeros(1,0))
%
% Description
%     Read type 1 output from an Abaqus results file generated from the
%     ABAQUS finite element software. The asterisk (*) is replaced by the
%     name of the results file. The possible values of recordKey can be
%     found from Table in section 3.2.2.2 of Abaqus2Matlab documentation.
%     The output of type 1 corresponds to records containing only floating
%     point numbers (no integers or strings). See section ''5.1.2 Results
%     file output format'' in ABAQUS Analysis User's manual for more
%     details.
%     Dummy input arguments are required for execution of this function, as
%     illustrated in the 'Input parameters' section below. These are used
%     for memory allocation issues and proper initialization of internal
%     variables.
%
% Input parameters
%     REQUIRED:
%     #Rec# (string) is a one-row string containing all the data inside the
%         Abaqus results file. The results file is generated by Abaqus
%         after the analysis has been completed.
%     #recordKey# (integer) is an integer equal to the record key of
%         the requested result. See the documentation for the possible
%         record keys for the extraction of results of type 1.
%     DUMMY (in the following order, after REQUIRED):
%     zeros(1,0)
%     zeros(1,0)
%
% Output parameters
%     #out# ([#n# x #m#]) is a double array containing the attributes of
%         the record key #recordKey#. If the results file does not contain
%         the requested output, #out# will be an empty array.
%
% _________________________________________________________________________
% Abaqus2Matlab - www.abaqus2matlab.com
% Copyright (c) 2017 by George Papazafeiropoulos
%
% If using this toolbox for research or industrial purposes, please cite:
% G. Papazafeiropoulos, M. Muniz-Calvente, E. Martinez-Paneda.
% Abaqus2Matlab: a suitable tool for finite element post-processing.
% Advances in Engineering Software. Vol 105. March 2017. Pages 9-16. (2017)
% DOI:10.1016/j.advengsoft.2017.01.006

% Built-in function (Matlab R2012b)
