%
% ABAQUS J-integral output to MATLAB
% 
% Syntax
%     [#EleOut1#,#NodeSetName#,#EleOut2#,#EleOut3#]=Rec1991(#Rec#,zeros(1,0),zeros(1,0))
%
% Description
%     Read J-integral output from the results file generated from the
%     ABAQUS finite element software. The record key for J-integral output
%     is 1991. See section ''Results file output format'' in ABAQUS
%     Analysis User's manual for more details.
%     The following options with parameters have to be specified in the
%     ABAQUS input file for the results file to be created and to
%     contain J-integral results:
%         *FILE FORMAT, ASCII
%         *EL FILE
%         JK
%     Dummy input arguments are required for execution of this function, as
%     illustrated in the 'Input parameters' section below. These are used
%     for memory allocation issues and proper initialization of internal
%     variables.
%     
% Input parameters
%     REQUIRED:
%     #Rec# (string) is a one-row string containing all the data inside the
%         Abaqus results file. The results file is generated by Abaqus
%         after the analysis has been completed.
%     DUMMY (in the following order, after REQUIRED):
%     zeros(1,0)
%     zeros(1,0)
% 
% Output parameters
%     #EleOut1# ([#n# x 1]) is a column vector containing the crack number.
%     #NodeSetName# ([#n# x 8]) is a string array having 8 characters per
%         row. Each row contains the name of the node set in A8 format,
%         left justified.
%     #EleOut2# ([#n# x 1]) is a column vector containing the number of
%         contours.
%     #EleOut3# ([#n# x #m#]) is an array containing #m# J-integral values
%         per row estimated by #m# contours.
%     #n# is the number of cracks multiplied by the crack front locations
%
% _________________________________________________________________________
% Abaqus2Matlab - www.abaqus2matlab.com
% Copyright (c) 2017 by George Papazafeiropoulos
%
% If using this toolbox for research or industrial purposes, please cite:
% G. Papazafeiropoulos, M. Muniz-Calvente, E. Martinez-Paneda.
% Abaqus2Matlab: a suitable tool for finite element post-processing.
% Advances in Engineering Software. Vol 105. March 2017. Pages 9-16. (2017) 
% DOI:10.1016/j.advengsoft.2017.01.006

% Built-in function (Matlab R2012b)
